### ISSUE TITLE
Crash when trying to load Model

### ISSUE THREAD

**Issue by Nilox42** [louisgv/local.ai#84]
I run my Instance on a brand-new Windows VM with 64 GB Ram and 22VCPU Cores. But when I try to load a model, the application crashes after a few seconds. I didn't find any logs, so I don't know what to do.

**Comment by louisgv** [comment]
@Nilox42 which version did you download btw? There's a bit of a refactor for GPU going on in #62, also which model did you tried?

**Comment by LLukas22** [comment]
Which cpu architecture does your Windows VM have? And does it support AVX2? Currently the main windows target for `rustformers` is a x86-64bit  machine with AVX2 support.

**Comment by Nilox42** [comment]
I used host, which is a "Xeon E5 2640", and x86-64-v2-AES. The Xeon does not support AVX2, so that's something I will look into.

**Comment by navr32** [comment]
Hello ! Crash  when try to inference....or when click on load..2x X5675 processor..24threads..96gb of ram..
So no AVX...could you build to be able to run without AVX..like llama.cpp do..or some others..like stablediffusion..invokeai ..and so ? many thanks because the projects looks very very good.
Have a nice days.

**Comment by LLukas22** [comment]
If you compile the app on your device without AVX support it should automatically exclude it from the build.

**Comment by navr32** [comment]
Yes ok ! i have done a try but on Manjaro Linux have to search for the good package and after some time the windows come up bug the windows stay White. 

![Capture d’écran du 2023-08-18 01-46-05](https://github.com/louisgv/local.ai/assets/1823291/5b85efee-5c7a-4835-82bc-6681b4b9b2c4)


No displays of the interface..but on localhost http://localhost:3047/ i have the localai website come on , and in 1407 the error message:

![Capture d’écran du 2023-08-18 01-40-12](https://github.com/louisgv/local.ai/assets/1823291/a23f70bb-da55-4b4c-92fd-cfd3122b9b65)

![Capture d’écran du 2023-08-18 01-42-34](https://github.com/louisgv/local.ai/assets/1823291/1746a472-0d68-4a85-8e0c-c3a0773fb913)

![Capture d’écran du 2023-08-18 01-43-04](https://github.com/louisgv/local.ai/assets/1823291/99a8cdd0-5f5c-4a19-b9dc-7f8e263f1a17)

![Capture d’écran du 2023-08-18 01-43-38](https://github.com/louisgv/local.ai/assets/1823291/20d8f07c-cc4f-4494-832a-1d8b906ea091)

So i have try on another more old computer with 4 thread processor 8go on Manjro just come of install...just again some package problem to found but the app come to life and with the dolly 2 model i can tchat but very long but work..so why this white windows on this systems ???

**Comment by navr32** [comment]
So i have clean all and try build again but same problem thing..and because i think curious i have the windows in grey with no design in it..? so i  have just try to resize several time and the label..tex..button..come to view...but some button are not drawn..in the model view no delete button or cloud at the left.. and when i want go frome thread and model manager  i have to resize the windows to haves interface become draw again...some have an advice ? wayland problem ? gtk ? graphic card amd rx580 problem ? nodesjs ?  thanks again...but now the inference is working..on this system but the interface drawing is "Lazy"..

**Comment by navr32** [comment]
I just try to trace the call with ltrace i have

 % time     seconds  usecs/call     calls      function
------ ----------- ----------- --------- --------------------
 66.93  320.562901        2938    109106 SYS_getegid32
 22.55  107.991411        2577     41900 SYS_waitpid

66% time in getegid32 ? and 22% waitpid ?  need to investigate more...

**Comment by louisgv** [comment]
Hmm... it compiles locally but doesn't work when bundle?? Which Distro are you running btw? Might need to follow the linux setup guide: https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux

**Comment by navr32** [comment]
No no ! it compile locally dev and bundle build work...but i must open another thread because the problem is another one.
Just now it use too many cpu on webkitprocess ...

**Comment by navr32** [comment]
So i think this issue can be close.. If i build localai with pnpm dev or pnpm build it start...but others problems come on ...blank windows..but if resize the windows for refresh ..the text in it come on..and buttons..so it's possible to use it..but hard to use...and the inference is working too..on different models...So perhaps the problem is in Tauri but if i build some other projects with tauri nextjs the app is working and no webkitprocess problem...so the problems seems to come just from the tauriapp of localai...
